version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # default user is "opam"
      - ..:/workspace:cached
      - opam:/home/opam/.opam:cached
      - build:/workspace/_build:cached
    environment:
      OPAMSOLVERTIMEOUT: 180
      VERSION: dev
    command: sleep infinity

  mailtrap:
    image: mailhog/mailhog
    container_name: mailtrap-letters
    hostname: mailtrap-letters
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  opam:
  build:
