name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Disable macos build for now since it keeps failing with dune not found
          # - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.14
          - 4.13
          - 4.12
          - 4.11
          - 4.10.1
          - 4.09
          - 4.08
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Retrieve opam cache
        uses: actions/cache@v4
        if: runner.os != 'Windows'
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-opam-${{ matrix.ocaml-compiler }}-${{ hashFiles('*.opam.locked') }}
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install dependencies
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          opam install -y dune
          opam install -y . --deps-only --with-doc --with-test --locked --update-invariant
      - name: Recover from an Opam broken state
        if: steps.cache-opam.outputs.cache-hit == 'true'
        run: |
          opam install -y dune
          opam upgrade --fixup
      - name: Build
        run: make build
      - name: Run tests
        run: make test
